== Anki 学习笔记

=== Cards

一问一答构成一张卡片。和纸质卡片一样的是，Anki 的卡片一面是问题，另一面是答案。和实际的纸质卡片不一样的是，当你显示答案时，默认情况下**问题仍然可见**。例如，如果你正在学习基础化学，你可能会看到如下问题：

[source,txt]
----
Q: Chemical symbol for oxygen?
----

问题是氧气的化学符号是什么? 你知道答案是大写字母 O，然后单击显示答案按钮，Anki 把问题和答案一块儿显示出来了：

[source,txt]
----
Q: Chemical symbol for oxygen?
A: O
----


=== Decks

牌(组)是一组卡片。您可以将卡片放在不同的牌组中来学习卡片集的部分内容，而不是一次性学习所有内容。每个牌组可以有不同的设置，例如每天要显示多少张新卡片，或者等多久卡片再次显示。

牌组可以包含其他牌组，这允许您将牌组组织成树。 Anki 使用 `::` 来显示不同的层级。名为 `Chinese::Hanzi` 的牌组引用了一个 `Hanzi` 牌组，它是 `Chinese` 牌组的一部分。如果你选择 `Hanzi`，那么只会显示汉字卡片; 如果选择 `Chinese`，则会显示所有中文卡片，包括汉字卡片。

要将牌组放入树形结构中，您可以在每个层级之间使用 `::`，或者将它们拖放到牌组列表中或从牌组列表中移除。已嵌套在另一个牌组下的牌组（即名称中至少有一个 `::`）通常称为子牌组，顶级牌组有时称为超级牌组或父牌组。

Anki 从一个名为 `Default` 的牌组开始; 任何不属于其它牌组的卡片都会出现在这里。如果 `Default`(默认)牌组不包含任何卡片并且你已添加其他牌组，那么 Anki 将隐藏默认牌组。或者，您可以重命名此默认牌组并将其用于其他卡片。

牌组最适合用于存放大类卡片，而不是特定主题，例如"食物动词"或"第1课"。有关这方面的更多信息，请参阅link:https://apps.ankiweb.net/docs/manual.html#manydecks[正确使用牌组]这一节。

有关牌组如何影响卡片顺序的信息，请参阅link:https://apps.ankiweb.net/docs/manual.html#displayorder[显示顺序]这一节。

=== Notes & Fields

制作卡片时，通常需要制作多张与某些信息相关的卡片。例如，如果你正在学习法语，并且你知道 `bonjour` 这个词的意思是 `你好`，你可能想创建一张显示 `bonjour` 以让你记住 `你好` 的卡片，另一张卡片显示 `你好` 以让你记住 `bonjour`。一张卡片测试你识别外语单词的能力，另一张卡片测试你产出单词的能力。

使用纸质卡片时，你唯有把它写两次，每张卡一次。一些计算机制卡程序提供了翻转正面和背面的功能, 生活不再枯燥。这是对纸质卡片的改进，但有两个主要缺点：

- 由于此类程序不会单独跟踪您的识别和产出，因此通常不会在最佳时间显示卡片，这意味着忘记的比记住的多，或者您学习的内容超出了必要的范围。

- 只有卡片正反面的内容完全相同时，才能翻转问题和答案。这意味着无法在每张卡的背面显示额外信息。

通过把卡片的内容分成单独的信息片段，Anki 解决了这些问题。然后，你告诉 Anki 要在每张卡上显示哪些信息，Anki 负责为你创建卡片，并在将来编辑卡片后更新它们。

假如我们想学习法语词汇，我们希望在每张卡片的背面都包含页码。我们希望卡片长这样：

[source,txt]
----
Q: Bonjour
A: Hello
   Page #12
----

和这样:

[source,txt]
----
Q: Hello
A: Bonjour
   Page #12
----

在此示例中，我们有三条相关信息：法语单词，英语含义和页码。如果我们将它们放在一起，它们看起来像这样：

[source,txt]
----
French: Bonjour
English: Hello
Page: 12
----

在 Anki 中，这种相关信息称为**记录**，每条信息称为字段。所以我们可以说这种类型的记录有三个字段：`French`，`English` 和 `Page`。

要添加和编辑字段，请在添加或编辑笔记时单击"字段..."按钮。有关字段的更多信息，请参阅link:https://apps.ankiweb.net/docs/manual.html#fields[自定义字段一节]。

=== Card Types

为了让 Anki 根据我们的记录创建卡片，我们需要给它一个蓝图，说明应该在每张卡片的正面或背面显示哪些字段。此蓝图称为卡片类型。每种类型的记录都可以有一种或多种卡片类型; 当您添加记录时，Anki 将为每种卡片类型创建一张卡片。

每种卡片类型都有两个模板，一个用于问题，另一个用于答案。在上面的法语示例中，我们希望识别卡看起来像这样：

[source,txt]
----
Q: Bonjour
A: Hello
   Page #12
----

为此，我们可以将问题和答案模板设置为：

[source,txt]
----
Q: {{French}}
A: {{English}}<br>
   Page #{{Page}}
----

通过用双花括号括起字段名，我们告诉 Anki 用该字段中的实际信息替换该部分。任何未被花括号括起来的东西保持不变。 （例如，我们不必在添加材料时在页面字段中键入 `Page #` - 它会自动添加到每张卡片上。）`<br>` 是一个特殊的代码，它告诉 Anki 移动到下一行; link:https://apps.ankiweb.net/docs/manual.html#templates[模板]一节提供了更多详细信息。

出产卡片模板以类似的方式工作：

[source,txt]
----
Q: {{English}}
A: {{French}}<br>
   Page #{{Page}}
----

`{{ ... }}` 类似于变量插值, 这很好理解。

创建卡片类型后，每次添加新记录时，都会根据该卡片类型创建卡片。卡片类型可以轻松保持卡片格式的一致性，并可以大大减少添加信息所需的工作量。它们还意味着 Anki 可以确保相关的卡片彼此之间不会显得过于接近，并且它们允许您修复输入错误或事实错误一次，并立即更新所有相关卡片。

要添加和编辑卡片类型，请在添加或编辑记录时单击"卡片..."按钮。有关卡片类型的更多信息，请参阅link:https://apps.ankiweb.net/docs/manual.html#templates[卡片和模板]一节。


=== Note Types

Anki 允许您为不同的材料创建不同类型的记录。每种类型的记录都有自己的字段和卡片类型。为您正在学习的每个广泛主题创建单独的记录类型是个好主意。在上面的法语示例中，我们可能会为此创建一个名为 `French` 的记录类型。如果我们想要学习首都城市，我们也可以为此创建一个单独的记录类型，其中包括"国家"和"首都"等字段。

当 Anki 检查重复时，它只比较相同类型的其他记录。因此，如果您使用首都城市记录类型添加名为 `Orange` 的首都城市，那么在学习如何用法语说 `Orange` 时，您将看不到重复的消息。

当您创建新集合时，Anki 会自动为其添加一些标准记录类型。提供这些记录类型是为了让新用户更容易使用 Anki，但从长远来看，建议您为正在学习的内容定义自己的记录类型。标准记录类型有如下几种：

- 基础

基础记录类型有正面和背面字段，并将创建一张卡片。您在正面输入的文字将显示在卡片的正面，而您在背面输入的文字将显示在卡片的背面。

- 基础（和翻转卡）

与 Basic 类似，但为你输入的文本创建两张卡片：一张从正面→背面，一张从背面→正面。

- 基础（可选翻转卡）

这是正面→背面卡，可选择背面→正面卡。为此，它有一个名为 `Add Reverse` 的第三个字段。如果在该字段中输入任何文本，将创建一个翻转卡。有关这方面的更多信息，请参见link:https://apps.ankiweb.net/docs/manual.html#templates[卡片和模板]一节。

- 完形填空

一种记录类型，可以轻松选择文本并将其转换为完形填空挖空（例如， "Man landed on the moon in […]" → "Man landed on the moon in 1969"）。link:https://apps.ankiweb.net/docs/manual.html#cloze[完形填空挖空]一节提供了更多信息。

要添加自己的记录类型并修改现有记录类型，可以使用 Anki 主窗口中的工具→管理记录类型。

记录和记录类型对于您的整个集合是通用的，而不仅限于单个牌组。这意味着您可以在特定牌组中使用许多不同类型的记录，或者使用不同卡片中的特定记录生成不同的卡片。使用"添加"窗口添加记录时，可以选择要使用的记录类型和要使用的牌组，这些选项完全相互独立。您还可以在link:https://apps.ankiweb.net/docs/manual.html#browsermisc[创建记录]后更改其记录类型。

记录有点像数据库中的一条记录, 每条记录有多个字段。

=== Collection

集合是 Anki 中存储的所有材料 - 卡片，记录，牌组，记录类型，牌组选项等。

=== 标签

字段最下面是标签, 可以为笔记添加多个标签, 标签之间用空格隔开:

[source,txt]
----
perl6 grammar regex
----

command + enter 将编辑好的一条笔记添加到牌组里。

</br> 添加换行

<div> </div> 添加块级别换行

{{FrontSide}} 表示正面的内容。

`hr` 用来在问题和答案之间画一条水平横线, 其作用是在显示答案的时候, 能够直接定位到答案部分。还可以为其添加上颜色: 

```
{{FrontSide}} </br>

<hr id=answer, color=red>

{{答}}
```

=== 答案检查

卡片正面

```
{{问}}
{{type:答}}
```

卡片背面

```
{{FrontSide}} </br>

<hr id=answer, color=red>

{{答}}
```

Anki 会为你生成一个答案输入框, 你必须输入一个答案, 然后 Anki 会用正确答案检查你的答案, 并标记出错误的地方。

=== 自定义字段的样式

卡片正面:

```
<div class=mycss>

{{问}}

</div>
```

格式刷:

```
.card {
 font-family: pingfang;
 font-size: 20px;
 text-align: center;
 color: black;
 background-color: white;
}

.mycss {
   font-family: kai;
   background-color: white;
}
```

=== 提示字段

首先先创建一个名为"提示"的字段, 并设置提示值。然后在模板里面添加一行 `{{hint:提示}}`:

[source,css]
----
<div class=mycss>

{{问}}

</div>
{{type:答}}

{{hint:提示}}
----

=== 特殊字段

- {{FrontSide}}, 正面模板的内容（仅在背面模板有效）
- {{Tags}}, 记录标签。
- {{Type}}, 记录类型。
- {{Deck}}, 所属记忆库（牌组）。
- {{Card}}, 卡片类型。


=== 基础类型

点击「添加」 -> 「类型」 -> 选择「基础」, 按 Command + L 进入 Anki 卡片模板编辑界面。